export const initialDefaultTeacherFields = [
  {
    name: "school_name",
    placeholder_text: "Enter school name",
    value_field: "",
    inputValue: "",
    title: "School/College Name",
    isAdded: true,
    placementOnPaper: "instatute_section",
  },
  {
    name: "subject",
    placeholder_text: "Enter subject",
    value_field: "",
    inputValue: "",
    title: "Subject",
    isAdded: true,
    placementOnPaper: "exam_details_section",
  },
  {
    name: "term_semester",
    placeholder_text: "Enter term/semester",
    value_field: "",
    inputValue: "",
    title: "Term/Semester",
    isAdded: true,
    placementOnPaper: "exam_title",
  },
  {
    name: "year",
    placeholder_text: "Enter the year",
    value_field: "",
    inputValue: "",
    title: "Year",
    isAdded: true,
    placementOnPaper: "exam_title",
  },
  {
    name: "class",
    placeholder_text: "Enter class",
    value_field: "",
    inputValue: "",
    title: "Class",
    isAdded: true,
    placementOnPaper: "exam_details_section",
  },
  {
    name: "type",
    placeholder_text: "Final",
    value_field: "",
    inputValue: "",
    title: "Type",
    isAdded: true,
    placementOnPaper: "exam_title",
  },
  {
    name: "number_of_marks",
    placeholder_text: "Enter number of marks",
    value_field: "",
    inputValue: "",
    title: "Number of Marks",
    isAdded: true,
    placementOnPaper: "exam_details_section",
  },
  {
    name: "day_of_exam",
    placeholder_text: "Enter day of the exam",
    value_field: "",
    inputValue: "",
    title: "Day of the Exam",
    isAdded: true,
    placementOnPaper: "exam_details_section",
  },
  {
    name: "date_of_exam",
    placeholder_text: "Enter date of the exam",
    value_field: "",
    inputValue: "",
    title: "Date of the Exam",
    isAdded: true,
    placementOnPaper: "exam_details_section",
  },
  {
    name: "duration_in_hours",
    placeholder_text: "Enter duration in hours",
    value_field: "",
    inputValue: "",
    title: "Duration in Hours",
    isAdded: true,
    placementOnPaper: "exam_details_section",
  },
];
export const initialOtherTeacherFields = [
  {
    name: "notes_instructions",
    placeholder_text: "Enter notes/instructions",
    value_field: "",
    inputValue: "",
    title: "Notes/Instructions",
    isAdded: false,
    placementOnPaper: "notes_section",
  },
  {
    name: "class_section",
    placeholder_text: "Enter class section",
    value_field: "",
    inputValue: "",
    title: "class_section",
    isAdded: false,
    placementOnPaper: "exam_details_section",
  },
  {
    name: "number_of_questions",
    placeholder_text: "Enter number of questions",
    value_field: "",
    inputValue: "",
    title: "Number of Questions",
    isAdded: false,
    placementOnPaper: "exam_details_section",
  },

  {
    name: "country",
    placeholder_text: "Enter country",
    value_field: "",
    inputValue: "",
    title: "Country",
    isAdded: false,
    placementOnPaper: "instatute_section",
  },
  {
    name: "number_of_page",
    placeholder_text: "Enter the number of pages",
    value_field: "",
    inputValue: "",
    title: "Number of pages",
    isAdded: false,
    placementOnPaper: "exam_details_section",
  },
  {
    name: "state_department_name",
    placeholder_text: "Enter state department name",
    value_field: "",
    inputValue: "",
    title: "State Department Name",
    isAdded: false,
    placementOnPaper: "instatute_section",
  },
  {
    name: "ministry_department_name",
    placeholder_text: "Enter ministry/department name",
    value_field: "",
    inputValue: "",
    title: "Ministry/Department Name",
    isAdded: false,
    placementOnPaper: "instatute_section",
  },
  {
    name: "logo",
    placeholder_text: "Upload logo",
    value_field: "",
    inputValue: "",
    title: "Logo",
    isAdded: false,
    placementOnPaper: "logo_section",
  },
];

export const initialDefaultStudentsFields = [
  {
    name: "std_name",
    placeholder_text: "Enter student name",
    value_field: "",
    inputValue: "الاسم:  ",
    title: "Student Name",
    isAdded: true,
    placementOnPaper: "student_section",
  },

  {
    name: "std_number",
    placeholder_text: "Enter student number",
    value_field: "",
    inputValue: "رقم الجلوس:  ",
    title: "Student Number",
    isAdded: false,
    placementOnPaper: "student_section",
  },
];
export const initialOtherStudentsFields = [
  {
    name: "std_class",
    placeholder_text: "Enter student class",
    value_field: "",
    inputValue: "الصف:  ",
    title: "Student Class",
    isAdded: false,
    placementOnPaper: "student_section",
  },
];
