import lang from "@/lib/examLanguage";
import headerLanguage from "@/lib/examLanguage/headerLanguage";

// the placeholder text should be follwing the locale
// the title also should also follow the locale
// the innnertext should follow the exam language

const examLang: "en" | "ar" = "en";

export const initialDefaultTeacherFields = [
  {
    name: "school_name",
    placeholder_text: headerLanguage["ar"].enterSchoolName,
    value_field: "",
    inputValue: "",
    title: headerLanguage["ar"].schoolName,
    isAdded: true,
    placementOnPaper: "instatute_section",
  },
  {
    name: "subject",
    placeholder_text: headerLanguage["ar"].enterSubject,
    value_field: "",
    inputValue: lang[examLang].subject,
    title: headerLanguage["ar"].subject,
    isAdded: true,
    placementOnPaper: "exam_details_section",
  },
  {
    name: "term_semester",
    placeholder_text: headerLanguage["ar"].enterTermSemester,
    value_field: "",
    inputValue: "",
    title: headerLanguage["ar"].termSemester,
    isAdded: true,
    placementOnPaper: "exam_title",
  },
  {
    name: "year",
    placeholder_text: headerLanguage["ar"].enterYear,
    value_field: "",
    inputValue: "",
    title: headerLanguage["ar"].year,
    isAdded: true,
    placementOnPaper: "exam_title",
  },
  {
    name: "class",
    placeholder_text: headerLanguage["ar"].enterClass,
    value_field: "",
    inputValue: "",
    title: headerLanguage["ar"].class,
    isAdded: true,
    placementOnPaper: "exam_details_section",
  },
  {
    name: "type",
    placeholder_text: headerLanguage["ar"].enterType,
    value_field: "",
    inputValue: "",
    title: headerLanguage["ar"].type,
    isAdded: true,
    placementOnPaper: "exam_title",
  },
  {
    name: "number_of_marks",
    placeholder_text: headerLanguage["ar"].enterNumberOfMarks,
    value_field: "",
    inputValue: "",
    title: headerLanguage["ar"].numberOfMarks,
    isAdded: true,
    placementOnPaper: "exam_details_section",
  },
  {
    name: "day_of_exam",
    placeholder_text: headerLanguage["ar"].enterDayOfExam,
    value_field: "",
    inputValue: lang[examLang].day,
    title: headerLanguage["ar"].dayOfExam,
    isAdded: true,
    placementOnPaper: "exam_details_section",
  },
  {
    name: "date_of_exam",
    placeholder_text: headerLanguage["ar"].enterDateOfExam,
    value_field: "",
    inputValue: lang[examLang].date,
    title: headerLanguage["ar"].dateOfExam,
    isAdded: true,
    placementOnPaper: "exam_details_section",
  },
  {
    name: "duration_in_hours",
    placeholder_text: headerLanguage["ar"].enterDurationInHours,
    value_field: "",
    inputValue: lang[examLang].time,
    title: headerLanguage["ar"].durationInHours,
    isAdded: true,
    placementOnPaper: "exam_details_section",
  },
];
export const initialOtherTeacherFields = [
  {
    name: "notes_instructions",
    placeholder_text: headerLanguage["ar"].enterNotesInstructions,
    value_field: "",
    inputValue: "",
    title: headerLanguage["ar"].notesInstructions,
    isAdded: false,
    placementOnPaper: "notes_section",
  },
  {
    name: "class_section",
    placeholder_text: headerLanguage["ar"].enterClassSection,
    value_field: "",
    inputValue: "",
    title: headerLanguage["ar"].classSection,
    isAdded: false,
    placementOnPaper: "exam_details_section",
  },
  {
    name: "number_of_questions",
    placeholder_text: headerLanguage["ar"].enterNumberOfQuestions,
    value_field: "",
    inputValue: "",
    title: headerLanguage["ar"].numberOfQuestions,
    isAdded: false,
    placementOnPaper: "exam_details_section",
  },

  {
    name: "faculty",
    placeholder_text: headerLanguage["ar"].faculty,
    value_field: "",
    inputValue: "",
    title: headerLanguage["ar"].faculty,
    isAdded: false,
    placementOnPaper: "instatute_section",
  },
  {
    name: "country",
    placeholder_text: headerLanguage["ar"].enterCountry,
    value_field: "",
    inputValue: "",
    title: headerLanguage["ar"].country,
    isAdded: false,
    placementOnPaper: "instatute_section",
  },
  {
    name: "number_of_page",
    placeholder_text: headerLanguage["ar"].enterNumberOfPages,
    value_field: "",
    inputValue: "",
    title: headerLanguage["ar"].numberOfPages,
    isAdded: false,
    placementOnPaper: "exam_details_section",
  },
  {
    name: "state_department_name",
    placeholder_text: headerLanguage["ar"].enterStateDepartmentName,
    value_field: "",
    inputValue: "",
    title: headerLanguage["ar"].stateDepartmentName,
    isAdded: false,
    placementOnPaper: "instatute_section",
  },
  {
    name: "ministry_department_name",
    placeholder_text: headerLanguage["ar"].enterMinistryDepartmentName,
    value_field: "",
    inputValue: "",
    title: headerLanguage["ar"].ministryDepartmentName,
    isAdded: false,
    placementOnPaper: "instatute_section",
  },
  {
    name: "logo",
    placeholder_text: headerLanguage["ar"].uploadLogo,
    value_field: "",
    inputValue: "",
    title: headerLanguage["ar"].logo,
    isAdded: false,
    placementOnPaper: "logo_section",
  },
];

export const initialDefaultStudentsFields = [
  {
    name: "std_name",
    placeholder_text: headerLanguage["ar"].enterStudentName,
    value_field: "",
    inputValue: lang[examLang].studentName,
    title: headerLanguage["ar"].studentName,
    isAdded: true,
    placementOnPaper: "student_section",
  },

  {
    name: "std_number",
    placeholder_text: headerLanguage["ar"].enterStudentNumber,
    value_field: "",
    inputValue: lang[examLang].studentId,
    title: headerLanguage["ar"].studentNumber,
    isAdded: false,
    placementOnPaper: "student_section",
  },
];
export const initialOtherStudentsFields = [
  {
    name: "std_class",
    placeholder_text: headerLanguage["ar"].studentClass,
    value_field: "",
    inputValue: lang[examLang].studentClass,
    title: headerLanguage["ar"].studentClass,
    isAdded: false,
    placementOnPaper: "student_section",
  },
];
