export const initialDefaultTeacherFields = [
  {
    name: "school_name",
    placeholder_text: "Enter school name",
    value_field: "",
    inputValue: "",
    title: "School/College Name",
    isAdded: true,
  },
  {
    name: "subject",
    placeholder_text: "Enter subject",
    value_field: "",
    inputValue: "",
    title: "Subject",
    isAdded: true,
  },
  {
    name: "term_semester",
    placeholder_text: "Enter term/semester",
    value_field: "",
    inputValue: "",
    title: "Term/Semester",
    isAdded: true,
  },
  {
    name: "class",
    placeholder_text: "Enter class",
    value_field: "",
    inputValue: "",
    title: "Class",
    isAdded: true,
  },
  {
    name: "type",
    placeholder_text: "Final",
    value_field: "",
    inputValue: "",
    title: "Type",
    isAdded: true,
  },
  {
    name: "number_of_marks",
    placeholder_text: "Enter number of marks",
    value_field: "",
    inputValue: "",
    title: "Number of Marks",
    isAdded: true,
  },
  {
    name: "day_of_exam",
    placeholder_text: "Enter day of the exam",
    value_field: "",
    inputValue: "",
    title: "Day of the Exam",
    isAdded: true,
  },
  {
    name: "date_of_exam",
    placeholder_text: "Enter date of the exam",
    value_field: "",
    inputValue: "",
    title: "Date of the Exam",
    isAdded: true,
  },
  {
    name: "duration_in_hours",
    placeholder_text: "Enter duration in hours",
    value_field: "",
    inputValue: "",
    title: "Duration in Hours",
    isAdded: true,
  },
];
export const initialOtherTeacherFields = [
  {
    name: "notes_instructions",
    placeholder_text: "Enter notes/instructions",
    value_field: "",
    inputValue: "",
    title: "Notes/Instructions",
    isAdded: false,
  },
  {
    name: "number_of_questions",
    placeholder_text: "Enter number of questions",
    value_field: "",
    inputValue: "",
    title: "Number of Questions",
    isAdded: false,
  },
  {
    name: "custom_field",
    placeholder_text: "Enter custom field",
    value_field: "",
    inputValue: "",
    title: "Custom Field",
    isAdded: false,
  },
  {
    name: "country",
    placeholder_text: "Enter country",
    value_field: "",
    inputValue: "",
    title: "Country",
    isAdded: false,
  },
  {
    name: "state_department_name",
    placeholder_text: "Enter state department name",
    value_field: "",
    inputValue: "",
    title: "State Department Name",
    isAdded: false,
  },
  {
    name: "ministry_department_name",
    placeholder_text: "Enter ministry/department name",
    value_field: "",
    inputValue: "",
    title: "Ministry/Department Name",
    isAdded: false,
  },
  {
    name: "teacher_name",
    placeholder_text: "Enter teacher's name",
    value_field: "",
    inputValue: "",
    title: "Teacher's Name",
    isAdded: false,
  },
  {
    name: "logo",
    placeholder_text: "Upload logo",
    value_field: "",
    inputValue: "",
    title: "Logo",
    isAdded: false,
  },
];

export const initialDefaultStudentsFields = [
  {
    name: "std_name",
    placeholder_text: "Enter student name",
    value_field: "",
    inputValue:
      "الاسم..................................................................",
    title: "Student Name",
    isAdded: true,
  },

  {
    name: "std_number",
    placeholder_text: "Enter student number",
    value_field: "",
    inputValue:
      "رقم الجلوس.........................................................",
    title: "Student Number",
    isAdded: true,
  },
];
export const initialOtherStudentsFields = [
  {
    name: "std_class",
    placeholder_text: "Enter student class",
    value_field: "",
    inputValue: "",
    title: "Student Class",
    isAdded: false,
  },
];
