/* eslint-disable react-hooks/rules-of-hooks */
"use client";
import lang from "@/lib/examLanguage";
import headerLanguage from "@/lib/examLanguage/headerLanguage";

const examLang: "en" | "ar" = "en";

export const getInititalTeacherInputs = (language: "en" | "ar") => [
  {
    name: "school_name",
    placeholder_text: headerLanguage[language].enterSchoolName,
    value_field: "",
    inputValue: "",
    title: headerLanguage[language].schoolName,
    isAdded: true,
    placementOnPaper: "instatute_section",
  },
  {
    name: "subject",
    placeholder_text: headerLanguage[language].enterSubject,
    value_field: "",
    inputValue: lang["ar"].subject,
    title: headerLanguage[language].subject,
    isAdded: true,
    placementOnPaper: "exam_details_section",
  },
  {
    name: "term_semester",
    placeholder_text: headerLanguage[language].enterTermSemester,
    value_field: "",
    inputValue: "",
    title: headerLanguage[language].termSemester,
    isAdded: true,
    placementOnPaper: "exam_title",
  },
  {
    name: "year",
    placeholder_text: headerLanguage[language].enterYear,
    value_field: "",
    inputValue: "",
    title: headerLanguage[language].year,
    isAdded: true,
    placementOnPaper: "exam_title",
  },
  {
    name: "class",
    placeholder_text: headerLanguage[language].enterClass,
    value_field: "",
    inputValue: "",
    title: headerLanguage[language].class,
    isAdded: true,
    placementOnPaper: "exam_details_section",
  },
  {
    name: "type",
    placeholder_text: headerLanguage[language].enterType,
    value_field: "",
    inputValue: "",
    title: headerLanguage[language].type,
    isAdded: true,
    placementOnPaper: "exam_title",
  },
  {
    name: "number_of_marks",
    placeholder_text: headerLanguage[language].enterNumberOfMarks,
    value_field: "",
    inputValue: "",
    title: headerLanguage[language].numberOfMarks,
    isAdded: true,
    placementOnPaper: "exam_details_section",
  },
  {
    name: "day_of_exam",
    placeholder_text: headerLanguage[language].enterDayOfExam,
    value_field: "",
    inputValue: lang["ar"].day,
    title: headerLanguage[language].dayOfExam,
    isAdded: true,
    placementOnPaper: "exam_details_section",
  },
  {
    name: "date_of_exam",
    placeholder_text: headerLanguage[language].enterDateOfExam,
    value_field: "",
    inputValue: lang["ar"].date,
    title: headerLanguage[language].dateOfExam,
    isAdded: true,
    placementOnPaper: "exam_details_section",
  },
  {
    name: "duration_in_hours",
    placeholder_text: headerLanguage[language].enterDurationInHours,
    value_field: "",
    inputValue: lang["ar"].time,
    title: headerLanguage[language].durationInHours,
    isAdded: true,
    placementOnPaper: "exam_details_section",
  },
];
export const getInitialTeacherButtons = (language: "en" | "ar") => [
  {
    name: "notes_instructions",
    placeholder_text: headerLanguage[language].enterNotesInstructions,
    value_field: "",
    inputValue: "",
    title: headerLanguage[language].notesInstructions,
    isAdded: false,
    placementOnPaper: "notes_section",
  },
  {
    name: "class_section",
    placeholder_text: headerLanguage[language].enterClassSection,
    value_field: "",
    inputValue: "",
    title: headerLanguage[language].classSection,
    isAdded: false,
    placementOnPaper: "exam_details_section",
  },
  {
    name: "number_of_questions",
    placeholder_text: headerLanguage[language].enterNumberOfQuestions,
    value_field: "",
    inputValue: "",
    title: headerLanguage[language].numberOfQuestions,
    isAdded: false,
    placementOnPaper: "exam_details_section",
  },

  {
    name: "faculty",
    placeholder_text: headerLanguage[language].faculty,
    value_field: "",
    inputValue: "",
    title: headerLanguage[language].faculty,
    isAdded: false,
    placementOnPaper: "instatute_section",
  },
  {
    name: "country",
    placeholder_text: headerLanguage[language].enterCountry,
    value_field: "",
    inputValue: "",
    title: headerLanguage[language].country,
    isAdded: false,
    placementOnPaper: "instatute_section",
  },
  {
    name: "number_of_page",
    placeholder_text: headerLanguage[language].enterNumberOfPages,
    value_field: "",
    inputValue: "",
    title: headerLanguage[language].numberOfPages,
    isAdded: false,
    placementOnPaper: "exam_details_section",
  },
  {
    name: "state_department_name",
    placeholder_text: headerLanguage[language].enterStateDepartmentName,
    value_field: "",
    inputValue: "",
    title: headerLanguage[language].stateDepartmentName,
    isAdded: false,
    placementOnPaper: "instatute_section",
  },
  {
    name: "ministry_department_name",
    placeholder_text: headerLanguage[language].enterMinistryDepartmentName,
    value_field: "",
    inputValue: "",
    title: headerLanguage[language].ministryDepartmentName,
    isAdded: false,
    placementOnPaper: "instatute_section",
  },
  {
    name: "logo",
    placeholder_text: headerLanguage[language].uploadLogo,
    value_field: "",
    inputValue: "",
    title: headerLanguage[language].logo,
    isAdded: false,
    placementOnPaper: "logo_section",
  },
];
export const getInitialStudentsInputs = (language: "en" | "ar") => [
  {
    name: "std_name",
    placeholder_text: headerLanguage[language].enterStudentName,
    value_field: "",
    inputValue: lang[examLang].studentName,
    title: headerLanguage[language].studentName,
    isAdded: true,
    placementOnPaper: "student_section",
  },

  {
    name: "std_number",
    placeholder_text: headerLanguage[language].enterStudentNumber,
    value_field: "",
    inputValue: lang[examLang].studentId,
    title: headerLanguage[language].studentNumber,
    isAdded: false,
    placementOnPaper: "student_section",
  },
];
export const getInitialOtherStudentsButtons = (language: "en" | "ar") => [
  {
    name: "std_class",
    placeholder_text: headerLanguage[language].studentClass,
    value_field: "",
    inputValue: lang[examLang].studentClass,
    title: headerLanguage[language].studentClass,
    isAdded: false,
    placementOnPaper: "student_section",
  },
];
